name: "ShowInfo"
main: ShowInfo.ShowInfo
version: "1.0.0"
api: ["1.0.0"]
author: "DeBe"
website: "http://github.com/NukkitPlugin/ShowInfo"

permissions:
  showinfo.*:
    children:
      showinfo.command.*:
        children:
          showinfo.command.showinfo:
            default: true
            children:
              showinfo.command.showinfo.on:
                default: true
              showinfo.command.showinfo.off:
                default: true
              showinfo.command.showinfo.start:
                default: op
              showinfo.command.showinfo.stop:
                default: op
              showinfo.command.showinfo.push:
                default: op
              showinfo.command.showinfo.tick:
                default: op
              showinfo.command.showinfo.oprank:
                default: op
              showinfo.command.showinfo.reload:
                default: op
              showinfo.command.showinfo.save:
                default: op
              showinfo.command.showinfo.reset:
                default: console